version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "HR-bot"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-dvgd7biuzuz3"
s3_prefix = "HR-bot"
region = "eu-central-1"
profile = "perfsys"
capabilities = "CAPABILITY_IAM"
